### ISSUE TITLE
Initialisation of project 

### ISSUE THREAD

**Issue by valeriia-z** [UniLuFS2020-ReplicationSeminar/HDS_Class_Ex_2#1]
Hello, girls!
Created repo for our project and connected to R Project.

Let's discuss possible ideas for what we want to scrape

**Comment by merclehoczky** [comment]
Let's do something about diets, do you have any specific interest in that topic?

**Comment by ViktoriiaTan** [comment]
We could scrape different type of diets and see the trends over time. I'm interested in popularity of vegan diet. Do you have any other ideas?

**Comment by merclehoczky** [comment]
Paleo?

**Comment by valeriia-z** [comment]
Good idea! I want to look for keto diet.
These three is enough I guess for nice graphs.

**Comment by ViktoriiaTan** [comment]
Then I can start with the scraping)

**Comment by merclehoczky** [comment]
I'll create the folders here in the meantime

**Comment by merclehoczky** [comment]
Folders done

**Comment by ViktoriiaTan** [comment]
I've written code to set API key and queries parameters
