### ISSUE TITLE
Way of scraping?

### ISSUE THREAD

**Issue by ViktoriiaTan** [UniLuFS2020-ReplicationSeminar/HDS_Class_Ex_2#2]
We can create a loop that will go through  query vector ("vegan,"keto","paleo") and  create a list that include 3 data frames inside or we can scrape each query separately in order to create 3 data frames. Which one way do you prefer more?

**Comment by ViktoriiaTan** [comment]
I tried a loop

**Comment by valeriia-z** [comment]
Nice, with loop it's more convenient. Glad we tried both.
