### ISSUE TITLE
Filtering data

### ISSUE THREAD

**Issue by merclehoczky** [UniLuFS2020-ReplicationSeminar/HDS_Class_Ex_2#4]
Hi
I will proceed with filtering data now

**Comment by merclehoczky** [comment]
I think the data is fairly clean, I only added 'Year' and 'month' columns so far. What do you think?

**Comment by ViktoriiaTan** [comment]
I think it's good. By having these we can check number of published articles over time

**Comment by valeriia-z** [comment]
Good, I'll look after your code soon.
