### ISSUE TITLE
Plots

### ISSUE THREAD

**Issue by merclehoczky** [UniLuFS2020-ReplicationSeminar/HDS_Class_Ex_2#6]
Hi
I'll start plotting such variables as:

- articles by month and year
- articles by section_name
- byline (author)
- wordcount
- production_office
- publication
- legally sensitive
- by diet

Let's share if we would add more :)

**Comment by merclehoczky** [comment]
I added plots for articles by topic and year, and by diet only, else the plots would have been too busy. 
Let me know what you think!

**Comment by merclehoczky** [comment]
I did not write a code for saving them, if you have time you could add that too

**Comment by valeriia-z** [comment]
Dear Mercedes, i think second plot is hard to read. Maybe play a bit with settings or make facet wrapping for some years? or make groups for 5-year period (2000-2005, and etc)?

i'll save plots once you're done

**Comment by ViktoriiaTan** [comment]
I will add plot with sentiment analysis. @valeriia-z and you can save it too)

**Comment by valeriia-z** [comment]
thank you @ViktoriiaTan, i will :)

**Comment by merclehoczky** [comment]
Added the interval version it to the main branch 
but let's proceed with the old version
